//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplyee
    {
        public int id { get; set; }
        public Nullable<int> Emplyecode { get; set; }
        public string Employename { get; set; }
        public string Desgntion { get; set; }
        public string Salary { get; set; }
    }
}
